### ISSUE TITLE
How to turn metadata to structured excel or tab separated tables? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [IHEC/ihec-metadata#4]
Hi dbujold, 

I want to do some further analysis based on IHEC methylation data. However, after I download the metadata, I don’t know how to read it. How to turn metadata to structured excel or tab separated tables? 

The metadata link:

http://epigenomesportal.ca/cgi-bin/api/getDataHub.py?session=8298

Thanks. 

Shicheng

**Comment by dbujold** [comment]
*Pasting reply sent by email*

Dear Shicheng,

JSON and Excel are quite different ways of representing information. 
JSON allows for more depth over multiple dimensions of data. Therefore 
it'd be difficult to write a converter from JSON to Excel without 
sacrificing some of the metadata. What are you trying to extract more 
exactly from the JSON document?

Sincerely,

David
