### ISSUE TITLE
Missing options in 'IHEC Metadata Specification (version 1.0)' - Experiment RNA-Seq

### ISSUE THREAD

**Issue by kevihiiin** [IHEC/ihec-metadata#7]
There are some inconsistencies between the supported values [by the validator](https://github.com/IHEC/ihec-ecosystems/blob/master/version_metadata/json_schema/experiment.json) and the [specification page](https://github.com/IHEC/ihec-metadata/blob/master/specs/Ihec_metadata_specification.md#rna-seq).

### experiment_types

Validator [link](https://github.com/IHEC/ihec-ecosystems/blob/8a6c090c8a2b8fd76604505ceb0574da0652b2be/version_metadata/json_schema/experiment.json#L149):
```json
"experiment_type": {"type": "string", "enum": ["RNA-Seq", "mRNA-Seq", "smRNA-Seq", "total-RNA-Seq"]},
```

Specification:
EXPERIMENT_TYPE: (Controlled Vocabulary) 'RNA-Seq'.

=> Missing: "mRNA-Seq", "smRNA-Seq", "total-RNA-Seq"

### library_strategy

Validator [link](https://github.com/IHEC/ihec-ecosystems/blob/8a6c090c8a2b8fd76604505ceb0574da0652b2be/version_metadata/json_schema/experiment.json#L151):

```json
": {"type": "string", "enum": ["RNA-Seq", "miRNA-Seq"]},
```

Specification:
LIBRARY_STRATEGY - (Controlled Vocabulary) 'RNA-Seq'.

=> Missing: "miRNA-Seq"

**Comment by sitag** [comment]
@kevihiiin Sorry.. this got dropped. Indeed there are inconsistencies. This should be resolved in the latest validator commits. If something is still off, please make an issue in the ecosystem repository as metadata group has been swallowed by ecosystems group, and all development is undertaken there.
